WITH PARTICIPATIONS_C AS(
    SELECT 
        ROW_NUMBER() OVER(PARTITION BY CATEGORY ORDER BY MAX(SCORE) DESC) AS RNK,
        PARTICIPANT_ID, 
        STUDENT_ID,
        CATEGORY,
        MAX(SCORE) AS SCORE
    FROM 
        PARTICIPATIONS
    GROUP BY 
        PARTICIPANT_ID, 
        STUDENT_ID,
        CATEGORY
    ORDER BY 
        CATEGORY DESC,
        MAX(SCORE) DESC
)
SELECT 
    P.CATEGORY,
    P.STUDENT_ID,
    S.NAME,
    S.COLLEGE_NAME,
    P.SCORE
FROM 
    STUDENTS S 
    JOIN PARTICIPATIONS_C P ON P.STUDENT_ID = S.ID
WHERE 
    RNK <= 3    
ORDER BY 
    P.CATEGORY ASC, 
    S.COLLEGE_NAME ASC